### ISSUE TITLE
Seperate natural creatives and CB creatives

### ISSUE THREAD

**Issue by alisolarflare** [TBMCPlugins/CreativeBoundaries#8]
Create a playerlist that stores all the CB creatives
Make boundaries only affect CB creatives

**Comment by NorbiPeti** [comment]
Actually there's no need for a playerlist - check if they have the "eseentials.gamemode" perm, and it they do, don't gm them, maybe don't even allow cbgm so it won't mess up.

**Comment by NorbiPeti** [comment]
Also for server builds, allow cbgm if the current WG region has the player as a member/owner.

**Comment by alisolarflare** [comment]
This issue was moved to TBMCPlugins/AliPresents#7
